---
- name: Update package cache
  apt:
    update_cache: yes
    state: latest

- name: Install required system sys_packages
  apt:
    name: "{{sys_packages}}"
    state: "present"

- name: Install Angular CLI globally
  npm:
    name: "@angular/cli"
    global: yes
    state: present
