name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ">=18.19.1"

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build Project
        run: npm run build --if-present
        working-directory: ./frontend

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/ed_25519
          chmod 600 ~/.ssh/ed_25519
          ssh-keyscan -t ed25519 ${{ secrets.HOST }} >> ~/.ssh/known_hosts
          cat >>~/.ssh/config <<END
          Host devserver
            HostName ${{ secrets.HOST }}
            User ${{ secrets.USER }}
            IdentityFile ~/.ssh/ed_25519
          END

      - name: Checkout the latest source code
        run: ssh devserver 'cd ~/parlor_app && git fetch && git reset --hard origin/main'

      - name: Deploy Angular Application
        run: |

          ssh devserver 'export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && cd ~/parlor_app/frontend && npm install && npm run build --if-present'
          ssh devserver 'sudo rm -rf /var/www/html/*'
          ssh devserver 'sudo cp -r ~/parlor_app/frontend/dist/parlor-fe/browser/* /var/www/html'
          ssh devserver 'sudo systemctl nginx -s reload'
